/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import Admin.*;
import config.PanelPrinter;
import config.Session;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import petcaresystemguic.loginForm;

/**
 *
 * @author Yisha
 */
public class receipt extends javax.swing.JFrame {

    /**
     * Creates new form individualPrinting
     */
    public receipt() {
        initComponents();
    }
    
    Color navcolor = new Color(51,51,51);
    Color hovercolor = new Color(102,102,102);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        page = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        uname = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        stype = new javax.swing.JTextField();
        rm = new javax.swing.JTextField();
        oname = new javax.swing.JTextField();
        meds = new javax.swing.JTextField();
        date = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        print1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/arrow1.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 90, 60));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel2.setText("R");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 30, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel3.setText("I");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 30, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel4.setText("N");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 30, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel5.setText("T");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 30, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel6.setText("I");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 30, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel7.setText("N");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 30, -1));

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel8.setText("G");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 30, -1));

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel9.setText("F");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 720, 30, -1));

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel10.setText("O");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 760, 30, -1));

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel11.setText("R");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 800, 30, -1));

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel12.setText("M");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 840, 30, -1));

        jLabel13.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel13.setText("S");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 880, 30, -1));

        jLabel14.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel14.setText("P");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 30, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 1170));

        page.setBackground(new java.awt.Color(255, 255, 255));
        page.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel15.setText("YISHA'S PET CLINIC");
        page.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 290, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/illustration_of_pet_care-removebg-preview.jpg"))); // NOI18N
        page.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 90, 90));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Whiteland Tuyan City of Naga, Cebu");
        page.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 310, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel18.setText("+639123456789");
        page.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 140, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/download__6_-removebg-preview (3).png"))); // NOI18N
        page.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 50, 40));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/download__7_-removebg-preview.png"))); // NOI18N
        page.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 470, 40));

        jLabel23.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/download__7_-removebg-preview.png"))); // NOI18N
        page.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 140, 460, 60));

        jLabel24.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel24.setText("Date:");
        page.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 80, 30));

        jLabel27.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel27.setText("Medication(s):");
        page.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 710, 140, -1));

        jLabel32.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel32.setText("Owner Name:");
        page.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 120, 30));

        jLabel33.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel33.setText("Pet Name:");
        page.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 120, 30));

        uname.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        page.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 220, 30));

        jLabel28.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel28.setText("Veterinarian:");
        page.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 120, 30));

        jLabel30.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel30.setText("Service Type:");
        page.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 140, 30));

        jLabel34.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel34.setText("Remarks:");
        page.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 100, -1));

        stype.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        stype.setBorder(null);
        stype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stypeActionPerformed(evt);
            }
        });
        page.add(stype, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 180, 30));

        rm.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        rm.setText(" ");
        rm.setBorder(null);
        rm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmActionPerformed(evt);
            }
        });
        page.add(rm, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 580, 310, 90));

        oname.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        oname.setBorder(null);
        oname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onameActionPerformed(evt);
            }
        });
        page.add(oname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 190, 30));

        meds.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        meds.setBorder(null);
        meds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medsActionPerformed(evt);
            }
        });
        page.add(meds, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 730, 330, 80));

        date.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        page.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 220, 30));

        pname.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        pname.setBorder(null);
        pname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnameActionPerformed(evt);
            }
        });
        page.add(pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 180, 30));

        jPanel1.add(page, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 680, 840));

        print1.setBackground(new java.awt.Color(51, 51, 51));
        print1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                print1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                print1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                print1MouseExited(evt);
            }
        });
        print1.setLayout(null);

        jLabel19.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 204, 204));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("PRINT");
        print1.add(jLabel19);
        jLabel19.setBounds(0, 10, 140, 30);

        jPanel1.add(print1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 920, 140, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 1010));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        AppointmentsAdmin appa = new AppointmentsAdmin();
        appa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void stypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stypeActionPerformed

    private void rmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rmActionPerformed

    private void onameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_onameActionPerformed

    private void medsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medsActionPerformed

    private void pnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnameActionPerformed

    private void print1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print1MouseClicked
     
JPanel myPanel =  new JPanel();
PanelPrinter pPrint =  new PanelPrinter(page);
pPrint.printPanel();
    }//GEN-LAST:event_print1MouseClicked

    private void print1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print1MouseEntered
        print1.setBackground(hovercolor);
    }//GEN-LAST:event_print1MouseEntered

    private void print1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print1MouseExited
        print1.setBackground(navcolor);
    }//GEN-LAST:event_print1MouseExited

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
Session sess = Session.getInstance();
if(sess.getUid() == 0){
    JOptionPane.showMessageDialog(null, "No account, Login First!");
    loginForm lf = new loginForm();
    lf.setVisible(true);
    this.dispose();           
} else {
    uname.setText(sess.getFname() + " " + sess.getLname()); // Combine first and last name
}

      }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new receipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField meds;
    public javax.swing.JTextField oname;
    private javax.swing.JPanel page;
    public javax.swing.JTextField pname;
    private javax.swing.JPanel print1;
    public javax.swing.JTextField rm;
    public javax.swing.JTextField stype;
    public javax.swing.JLabel uname;
    // End of variables declaration//GEN-END:variables
}
